- name: Add device
  become: False
  community.general.xml:
    path: ~/config.xml
    # path: ~/.config/syncthing/config.xml
    xpath: /configuration/device
    attribute: id
    value: "{{ hostvars[item].device_id.stdout }}"
  register: added_device

- name: Add default device config
  become: False
  community.general.xml:
    path: ~/config.xml
    xpath: /configuration/device[@id='{{ hostvars[item].device_id.stdout }}']
    pretty_print: True
    input_type: xml
    set_children:
      - <address>dynamic</address>
      - <paused>false</paused>
      - <autoAcceptFolders>false</autoAcceptFolders>
      - <maxSendKbps>0</maxSendKbps>
      - <maxRecvKbps>0</maxRecvKbps>
      - <maxRequestKiB>0</maxRequestKiB>
      - <untrusted>false</untrusted>
      - <remoteGUIPort>0</remoteGUIPort>
  when: added_device.changed
# <device id="NTDPAK4-YSXAPDI" name="DESKTOP" compression="metadata" introducer="false" skipIntroductionRemovals="false" introducedBy="">
