---
- name: Add syncthing repository
  block:
    - name: Add syncthing repository
      copy:
        content: |
          deb https://apt.syncthing.net/ syncthing release
        dest: /etc/apt/sources.list.d/syncthing.list

    - name: Pin syncthing repository priority
      copy:
        content: |
          Package: *
          Pin: origin apt.syncthing.net
          Pin-Priority: 990
        dest: /etc/apt/preferences.d/syncthing

    - name: Add syncthing repository key
      apt_key:
        url: https://syncthing.net/release-key.txt
        state: present

- name: Install syncthing
  apt:
    update_cache: yes
    state: present
    name:
      - apt-transport-https
      - syncthing
  notify:
    - Enable syncthing service
    - Restart syncthing service

- name: Stop syncthing service
  service:
    name: "syncthing@{{ service_instance_name | default(ansible_user_id) }}"
    state: stopped

- name: Instruct service to wait for time sync after boot
  block:
  - name: Create drop-in directory
    file:
      path: /etc/systemd/system/syncthing@.service.d
      state: directory
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx

  - name: Create drop-in to instruct service to wait for time sync after boot
    copy:
      content: |
        [Unit]
        Wants=systemd-time-wait-sync.service
        After=systemd-time-wait-sync.service
      dest: /etc/systemd/system/syncthing@.service.d/override.conf
      owner: root
      group: root
      mode: u=rw,g=r,o=r
    notify:
      - Enable syncthing service
      - Restart syncthing service
  when: wait_for_time_sync is defined and wait_for_time_sync == True

- name: Install lxml dependencies
  apt:
    update_cache: yes
    state: present
    name:
      - python-lxml
  when: gui_address is defined

- name: Set GUI address
  become: False
  community.general.xml:
    path: ~/.config/syncthing/config.xml
    xpath: /configuration/gui/address
    value: "{{ gui_address }}"
  when: gui_address is defined


#     sed -i 's/<address>127.0.0.1:8384<\/address>/<address>0.0.0.0:8384<\/address>/g' ~/.config/syncthing/config.xml


# sudo env SYSTEMD_EDITOR="cp $HOME/tmp/syncthing-override.conf" systemctl edit syncthing@pi.service
#     sudo systemctl restart syncthing@pi.service